version: '3.6'
services:
  license-audit:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.license-audit

  android-gradle-plugin-ci-v8:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.android-ci
      args:
        - REG_BASIC_CREDENTIAL
        - REG_NPM_EMAIL
        - REG_URL
